version: "3.9"
services:
  ai-backend:
    build: ./ai-backend
    container_name: ai-backend
    ports:
      - "5001:5001"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
    restart: always

  ui-backend:
    build: ./ui-backend
    container_name: ui-backend
    ports:
      - "5000:5000"
    depends_on:
      - ai-backend
    environment:
      - AI_BACKEND_URL=http://ai-backend:5001
    restart: always
